# Generated by Django 3.2.20 on 2024-01-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friend_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codeforces_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
