# Generated by Django 3.2.20 on 2023-07-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230726_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
